# Generated by Django 4.1.5 on 2023-01-25 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AddField(
            model_name='language',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/language_images'),
        ),
        migrations.AddField(
            model_name='language',
            name='description_field',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='languages.category'),
        ),
    ]
