# Generated by Django 4.1.5 on 2023-01-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_category_alter_language_options_language_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='Image',
            new_name='image',
        ),
    ]
