# Generated by Django 4.1.5 on 2023-02-27 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0004_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
