# Generated by Django 4.1.5 on 2023-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_language_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_detail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
