# Generated by Django 4.1.5 on 2023-02-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0006_language_detail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_detail',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='language_detail',
            name='country',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='language_detail',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='language_detail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
