# Generated by Django 4.1.5 on 2023-03-03 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0007_language_detail_city_language_detail_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(default=1)),
                ('country', models.CharField(default=False, max_length=225)),
                ('city', models.CharField(blank=True, max_length=225)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='languages.languageorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='languages.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Language_detail',
        ),
    ]
