# Generated by Django 4.1.5 on 2023-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_rename_product_languageorderitem_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
