# Generated by Django 4.1.5 on 2023-03-10 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0011_remove_language_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageorder',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='languageorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
