# Generated by Django 4.1.5 on 2023-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_remove_languageorderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/language_images/thumbnails'),
        ),
    ]
