# Generated by Django 4.1.5 on 2023-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_language_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageorder',
            name='country',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
