# Generated by Django 4.1.5 on 2023-04-02 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0015_alter_languageorder_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
