# Generated by Django 4.1.5 on 2023-04-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0017_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_by',
            new_name='author',
        ),
    ]
