# Generated by Django 4.1.5 on 2023-04-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0018_rename_created_by_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='languages.language'),
        ),
    ]
