# Generated by Django 4.1.5 on 2023-05-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0020_remove_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
