# Generated by Django 4.1.5 on 2023-05-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0023_remove_blog_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='languages.language'),
        ),
    ]
