# Generated by Django 4.1.5 on 2023-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0024_blog_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
