# Generated by Django 4.1.5 on 2023-05-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0026_blogcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
