# Generated by Django 4.1.5 on 2023-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0028_alter_blog_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageorder',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languageorder',
            name='title',
        ),
        migrations.AlterField(
            model_name='languageorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
