# Generated by Django 4.1.5 on 2023-05-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0029_remove_languageorder_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
