# Generated by Django 4.1.5 on 2023-05-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0030_blog_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageorder',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_order', to='languages.language'),
        ),
    ]
