# Generated by Django 4.1.5 on 2023-05-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0031_languageorder_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageorderitem',
            old_name='order',
            new_name='language_order',
        ),
    ]
