# Generated by Django 4.1.5 on 2023-05-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0032_rename_order_languageorderitem_language_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
