# Generated by Django 4.1.5 on 2023-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0033_rename_user_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
