# Generated by Django 4.1.5 on 2023-05-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0034_blog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
