# Generated by Django 4.1.5 on 2023-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0036_remove_language_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
