# Generated by Django 4.2.1 on 2023-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0039_notepad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
