# Generated by Django 4.1.5 on 2023-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'draft'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
